version: 0.2.0.{build}-{branch}
branches:
  except:
    - gh-pages
image: Visual Studio 2017
before_build:
  - dotnet restore
matrix:
  fast_finish: true
configuration:
  - Debug
  - Release
test: off
